package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.BlackUrlHistoryData;

public interface BlackUrlHistoryDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_history_data
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int insert(BlackUrlHistoryData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_history_data
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int insertSelective(BlackUrlHistoryData record);
}