package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.BlackUrlDistributeTable;
import com.gcexe.qqdata.persistence.entity.BlackUrlDistributeTableKey;

public interface BlackUrlDistributeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_distribute_table
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int deleteByPrimaryKey(BlackUrlDistributeTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_distribute_table
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int insert(BlackUrlDistributeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_distribute_table
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int insertSelective(BlackUrlDistributeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_distribute_table
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    BlackUrlDistributeTable selectByPrimaryKey(BlackUrlDistributeTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_distribute_table
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int updateByPrimaryKeySelective(BlackUrlDistributeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_distribute_table
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int updateByPrimaryKey(BlackUrlDistributeTable record);
}