package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.BlackUrlEvilclassDistribute;

public interface BlackUrlEvilclassDistributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_evilclass_distribute
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int insert(BlackUrlEvilclassDistribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_url_evilclass_distribute
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    int insertSelective(BlackUrlEvilclassDistribute record);
}