package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.DdosCntHistoryKey;

public interface DdosCntHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddos_cnt_history
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    int deleteByPrimaryKey(DdosCntHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddos_cnt_history
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    int insert(DdosCntHistoryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddos_cnt_history
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    int insertSelective(DdosCntHistoryKey record);
}