package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.DdosNewCntHistoryKey;

public interface DdosNewCntHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddos_new_cnt_history
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    int deleteByPrimaryKey(DdosNewCntHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddos_new_cnt_history
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    int insert(DdosNewCntHistoryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddos_new_cnt_history
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    int insertSelective(DdosNewCntHistoryKey record);
}