package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.MobileVirusProvinceCityStatHistoryKey;

public interface MobileVirusProvinceCityStatHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_virus_province_city_stat_history
     *
     * @mbggenerated Fri Apr 20 15:49:32 CST 2018
     */
    int deleteByPrimaryKey(MobileVirusProvinceCityStatHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_virus_province_city_stat_history
     *
     * @mbggenerated Fri Apr 20 15:49:32 CST 2018
     */
    int insert(MobileVirusProvinceCityStatHistoryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_virus_province_city_stat_history
     *
     * @mbggenerated Fri Apr 20 15:49:32 CST 2018
     */
    int insertSelective(MobileVirusProvinceCityStatHistoryKey record);
}