package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.PcVirusProvinceCityStatHistoryKey;

public interface PcVirusProvinceCityStatHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_virus_province_city_stat_history
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    int deleteByPrimaryKey(PcVirusProvinceCityStatHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_virus_province_city_stat_history
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    int insert(PcVirusProvinceCityStatHistoryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_virus_province_city_stat_history
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    int insertSelective(PcVirusProvinceCityStatHistoryKey record);
}