package com.gcexe.qqdata.persistence.dao;

import com.gcexe.qqdata.persistence.entity.PcVirusTypeStatHistoryKey;

public interface PcVirusTypeStatHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_virus_type_stat_history
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    int deleteByPrimaryKey(PcVirusTypeStatHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_virus_type_stat_history
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    int insert(PcVirusTypeStatHistoryKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_virus_type_stat_history
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    int insertSelective(PcVirusTypeStatHistoryKey record);
}