package com.gcexe.qqdata.persistence.entity;

import java.util.Date;

public class BlackUrlDistributeTableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_table.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_table.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_table.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Integer evilclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_table.eviltype
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Integer eviltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_table.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_table.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_table.city
     *
     * @return the value of black_url_distribute_table.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_table.city
     *
     * @param city the value for black_url_distribute_table.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_table.country
     *
     * @return the value of black_url_distribute_table.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_table.country
     *
     * @param country the value for black_url_distribute_table.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_table.evilclass
     *
     * @return the value of black_url_distribute_table.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Integer getEvilclass() {
        return evilclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_table.evilclass
     *
     * @param evilclass the value for black_url_distribute_table.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setEvilclass(Integer evilclass) {
        this.evilclass = evilclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_table.eviltype
     *
     * @return the value of black_url_distribute_table.eviltype
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Integer getEviltype() {
        return eviltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_table.eviltype
     *
     * @param eviltype the value for black_url_distribute_table.eviltype
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setEviltype(Integer eviltype) {
        this.eviltype = eviltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_table.province
     *
     * @return the value of black_url_distribute_table.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_table.province
     *
     * @param province the value for black_url_distribute_table.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_table.ts
     *
     * @return the value of black_url_distribute_table.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_table.ts
     *
     * @param ts the value for black_url_distribute_table.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}