package com.gcexe.qqdata.persistence.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BlackUrlEvilclassDistribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_evilclass_distribute.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_evilclass_distribute.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_evilclass_distribute.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_evilclass_distribute.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Integer evilclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_evilclass_distribute.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Integer cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_evilclass_distribute.ratio
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private BigDecimal ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_evilclass_distribute.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_evilclass_distribute.country
     *
     * @return the value of black_url_evilclass_distribute.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_evilclass_distribute.country
     *
     * @param country the value for black_url_evilclass_distribute.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_evilclass_distribute.province
     *
     * @return the value of black_url_evilclass_distribute.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_evilclass_distribute.province
     *
     * @param province the value for black_url_evilclass_distribute.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_evilclass_distribute.city
     *
     * @return the value of black_url_evilclass_distribute.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_evilclass_distribute.city
     *
     * @param city the value for black_url_evilclass_distribute.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_evilclass_distribute.evilclass
     *
     * @return the value of black_url_evilclass_distribute.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Integer getEvilclass() {
        return evilclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_evilclass_distribute.evilclass
     *
     * @param evilclass the value for black_url_evilclass_distribute.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setEvilclass(Integer evilclass) {
        this.evilclass = evilclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_evilclass_distribute.cnt
     *
     * @return the value of black_url_evilclass_distribute.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_evilclass_distribute.cnt
     *
     * @param cnt the value for black_url_evilclass_distribute.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_evilclass_distribute.ratio
     *
     * @return the value of black_url_evilclass_distribute.ratio
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public BigDecimal getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_evilclass_distribute.ratio
     *
     * @param ratio the value for black_url_evilclass_distribute.ratio
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setRatio(BigDecimal ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_evilclass_distribute.ts
     *
     * @return the value of black_url_evilclass_distribute.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_evilclass_distribute.ts
     *
     * @param ts the value for black_url_evilclass_distribute.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}