package com.gcexe.qqdata.persistence.entity;

import java.util.Date;

public class BlackUrlDistributeCompareTableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_compare_table.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_compare_table.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_compare_table.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_compare_table.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_compare_table.city
     *
     * @return the value of black_url_distribute_compare_table.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_compare_table.city
     *
     * @param city the value for black_url_distribute_compare_table.city
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_compare_table.country
     *
     * @return the value of black_url_distribute_compare_table.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_compare_table.country
     *
     * @param country the value for black_url_distribute_compare_table.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_compare_table.province
     *
     * @return the value of black_url_distribute_compare_table.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_compare_table.province
     *
     * @param province the value for black_url_distribute_compare_table.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_compare_table.ts
     *
     * @return the value of black_url_distribute_compare_table.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_compare_table.ts
     *
     * @param ts the value for black_url_distribute_compare_table.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}