package com.gcexe.qqdata.persistence.entity;

import java.util.Date;

public class BlackUrlHistoryData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_history_data.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_history_data.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_history_data.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Integer evilclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_history_data.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Integer cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_history_data.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_history_data.country
     *
     * @return the value of black_url_history_data.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_history_data.country
     *
     * @param country the value for black_url_history_data.country
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_history_data.province
     *
     * @return the value of black_url_history_data.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_history_data.province
     *
     * @param province the value for black_url_history_data.province
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_history_data.evilclass
     *
     * @return the value of black_url_history_data.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Integer getEvilclass() {
        return evilclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_history_data.evilclass
     *
     * @param evilclass the value for black_url_history_data.evilclass
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setEvilclass(Integer evilclass) {
        this.evilclass = evilclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_history_data.cnt
     *
     * @return the value of black_url_history_data.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_history_data.cnt
     *
     * @param cnt the value for black_url_history_data.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_history_data.ts
     *
     * @return the value of black_url_history_data.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_history_data.ts
     *
     * @param ts the value for black_url_history_data.ts
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}