package com.gcexe.qqdata.persistence.entity;

public class BlackUrlDistributeTable extends BlackUrlDistributeTableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_url_distribute_table.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    private Integer cnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_url_distribute_table.cnt
     *
     * @return the value of black_url_distribute_table.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_url_distribute_table.cnt
     *
     * @param cnt the value for black_url_distribute_table.cnt
     *
     * @mbggenerated Sat Apr 21 17:47:07 CST 2018
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }
}