package com.gcexe.qqdata.persistence.entity;

import java.util.Date;

public class DdosCptTenDayHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddos_cpt_ten_day_history.city
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddos_cpt_ten_day_history.cnt
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    private Integer cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddos_cpt_ten_day_history.country
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddos_cpt_ten_day_history.province
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddos_cpt_ten_day_history.ts
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddos_cpt_ten_day_history.city
     *
     * @return the value of ddos_cpt_ten_day_history.city
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddos_cpt_ten_day_history.city
     *
     * @param city the value for ddos_cpt_ten_day_history.city
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddos_cpt_ten_day_history.cnt
     *
     * @return the value of ddos_cpt_ten_day_history.cnt
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddos_cpt_ten_day_history.cnt
     *
     * @param cnt the value for ddos_cpt_ten_day_history.cnt
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddos_cpt_ten_day_history.country
     *
     * @return the value of ddos_cpt_ten_day_history.country
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddos_cpt_ten_day_history.country
     *
     * @param country the value for ddos_cpt_ten_day_history.country
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddos_cpt_ten_day_history.province
     *
     * @return the value of ddos_cpt_ten_day_history.province
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddos_cpt_ten_day_history.province
     *
     * @param province the value for ddos_cpt_ten_day_history.province
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddos_cpt_ten_day_history.ts
     *
     * @return the value of ddos_cpt_ten_day_history.ts
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddos_cpt_ten_day_history.ts
     *
     * @param ts the value for ddos_cpt_ten_day_history.ts
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}