package com.gcexe.qqdata.persistence.entity;

import java.util.Date;

public class DdosNewCntHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddos_new_cnt_history.cnt
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    private Integer cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddos_new_cnt_history.ts
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddos_new_cnt_history.cnt
     *
     * @return the value of ddos_new_cnt_history.cnt
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddos_new_cnt_history.cnt
     *
     * @param cnt the value for ddos_new_cnt_history.cnt
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddos_new_cnt_history.ts
     *
     * @return the value of ddos_new_cnt_history.ts
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddos_new_cnt_history.ts
     *
     * @param ts the value for ddos_new_cnt_history.ts
     *
     * @mbggenerated Sat Apr 21 16:28:14 CST 2018
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}