package com.gcexe.qqdata.persistence.entity;

import java.util.Date;

public class PcVirustypeProvinceStatHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_virustype_province_stat_history.cnt
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    private Integer cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_virustype_province_stat_history.province
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_virustype_province_stat_history.ts
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_virustype_province_stat_history.virus_type
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    private String virusType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_virustype_province_stat_history.cnt
     *
     * @return the value of pc_virustype_province_stat_history.cnt
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_virustype_province_stat_history.cnt
     *
     * @param cnt the value for pc_virustype_province_stat_history.cnt
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_virustype_province_stat_history.province
     *
     * @return the value of pc_virustype_province_stat_history.province
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_virustype_province_stat_history.province
     *
     * @param province the value for pc_virustype_province_stat_history.province
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_virustype_province_stat_history.ts
     *
     * @return the value of pc_virustype_province_stat_history.ts
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_virustype_province_stat_history.ts
     *
     * @param ts the value for pc_virustype_province_stat_history.ts
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_virustype_province_stat_history.virus_type
     *
     * @return the value of pc_virustype_province_stat_history.virus_type
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public String getVirusType() {
        return virusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_virustype_province_stat_history.virus_type
     *
     * @param virusType the value for pc_virustype_province_stat_history.virus_type
     *
     * @mbggenerated Fri Apr 20 15:53:28 CST 2018
     */
    public void setVirusType(String virusType) {
        this.virusType = virusType;
    }
}